name: alzilzal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # localization
  cached_network_image: ^3.3.1
  # State managements
  provider: ^6.1.2
  # equatable
  # dartz
  dartz: ^0.10.1
  # cach
  shared_preferences: ^2.2.3
  #share
  share: ^2.0.4
  #rename
  rename: ^3.0.2
  #ui
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_iconly: null
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  intl_utils: ^2.8.7
  # barcode
  barcode_widget: ^2.0.4
  flutter_barcode_scanner:
  # notification
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  # pdf
  pdf: ^3.10.8 # Check for the latest version
  printing: ^5.12.0 # For printing and previewing
  # bloc
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  #Code generation for immutable classes
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  #dependency injection
  get_it: ^7.6.7
  # Networking
  dio: ^5.4.3+1
  bottom_picker: ^2.8.0

  #localiztion
  intl: ^0.19.0
  #google fonts
  google_fonts: ^6.2.0
  # screen utils for responsive design
  flutter_screenutil: ^5.9.0
  #loading_indicator
  loading_indicator: ^3.1.1
  #url launch
  url_launcher: ^6.2.5
  # icons
  icons_plus: ^5.0.0
  #equatable for models
  equatable: ^2.0.5
  # smooth page indicator for page view
  smooth_page_indicator: ^1.1.0
  # to get  card scanner
  permission_handler: ^11.3.0
  # to cache images
  fluttertoast: ^8.2.5
  # custom bottom nativation bar
  custom_navigation_bar: ^0.8.2
  # scan_code qr code
  mobile_scanner: ^4.0.1
  # qr code overlay
  qr_scanner_overlay: ^0.0.2
  archive: ^3.6.1
  args: ^2.5.0
  # to show request details
  pretty_dio_logger: ^1.3.1
  # to make animated fab icon
  conditional_builder_null_safety: ^0.0.6
  #win32:
  win32: ^5.5.4
  analyzer: ^6.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1




flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.jpg"
  remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icons/
    - assets/images/profile/
    - assets/images/
    - assets/images/categories/

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
