// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL1gjn2bvJ9qwNW8-c13RvrCwFUO2LxCI',
    appId: '1:531012176729:web:29710646b593ec0229da48',
    messagingSenderId: '531012176729',
    projectId: 'al-zilzal',
    authDomain: 'al-zilzal.firebaseapp.com',
    storageBucket: 'al-zilzal.appspot.com',
    measurementId: 'G-3P2YP3CQBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_kezedvEkCrjBR0a_EtxD53P7vc-O4Y',
    appId: '1:531012176729:android:e8e12f41f099c11729da48',
    messagingSenderId: '531012176729',
    projectId: 'al-zilzal',
    storageBucket: 'al-zilzal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbaQPHS9dhOKA99foNytSawHg0StfqQ1c',
    appId: '1:531012176729:ios:04630da3075f92d529da48',
    messagingSenderId: '531012176729',
    projectId: 'al-zilzal',
    storageBucket: 'al-zilzal.appspot.com',
    iosBundleId: 'com.example.alzilzal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbaQPHS9dhOKA99foNytSawHg0StfqQ1c',
    appId: '1:531012176729:ios:1e4c5a247a7bfd3429da48',
    messagingSenderId: '531012176729',
    projectId: 'al-zilzal',
    storageBucket: 'al-zilzal.appspot.com',
    iosBundleId: 'com.example.alzilzal.RunnerTests',
  );
}
